### ISSUE TITLE
Migrate to portage-2.3 / repoman-2.3

### ISSUE THREAD

**Issue by trofi** [mrueg/repoman-travis#10]
Starting from portage-2.3.0_rc1-r1 repoman is no longer a part of portage.
Additional package will be needed to be fetched.

**Comment by mrueg** [comment]
I'm currently busy, this will have to wait until August. I'm happy to merge pull requests.

**Comment by mrueg** [comment]
Resolved in https://github.com/mrueg/repoman-travis/commit/f355c757042327108757ea7d18bc512255b4a872
