### ISSUE TITLE
huge overlay timeout

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mrueg/repoman-travis#17]
The ros/ros-overlay instance keeps failing with:

> The job exceeded the maximum time limit for jobs, and has been terminated.

example https://travis-ci.org/ros/ros-overlay/builds/260823850?utm_source=github_status&utm_medium=notification

**Comment by Alessandro-Barbieri** [comment]
The ros/ros-overlay instance keeps failing with:

> The job exceeded the maximum time limit for jobs, and has been terminated.

example https://travis-ci.org/ros/ros-overlay/builds/260823850?utm_source=github_status&utm_medium=notification

**Comment by mrueg** [comment]
There's nothing I can do about it. I suggest to wait for https://github.com/gentoo/portage/tree/repoman and then remove checks that have a high cost.

**Comment by Alessandro-Barbieri** [comment]
Wait for what?
