### ISSUE TITLE
Build fails due to change of default portage directory

### ISSUE THREAD

**Issue by ferki** [mrueg/repoman-travis#40]
After updating `.travis.yml` with the recent `PORTAGE_VER="2.3.65` setting, Travis CI builds seem to fail with the following error:

```
$ ./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full -d"
!!! Section 'gentoo' in repos.conf has location attribute set to nonexistent directory: '/var/db/repos/gentoo'
!!! Invalid Repository Location (not a dir): '/var/db/repos/gentoo'
!!! Section 'gentoo' in repos.conf has location attribute set to nonexistent directory: '/var/db/repos/gentoo'
!!! Invalid Repository Location (not a dir): '/var/db/repos/gentoo'
[CRITICAL] Couldn't find licenses?
The command "./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full -d"" exited with 1
```

=sys-apps/portage-2.3.64 mentions in its changelog that:

> New (council approved) default locations for the Gentoo repository
[...]
/usr/portage -> /var/db/repos/gentoo".

Simply adding `PORTDIR=/usr/portage` to `.travis.yml` seems to help at least as a workaround, and I'll shortly send a PR with that.

**Comment by mrueg** [comment]
Portdir might not be ideal, I'll experiment a bit

**Comment by alexws54tk** [comment]
Confirm. Adding `PORTDIR=/usr/portage` is help me.

**Comment by ferki** [comment]
@mrueg: I agree that (ab)using `PORTDIR` is more of a workaround, so I made it to work with the new default directories. I believe that would be a more correct approach, but feel free to let me know if you have anything else in mind.

@alexws54tk: I'm glad the `PORTDIR` method worked for you! I thought you might be interested in trying out the patch on #42 as well. If you do, feel free to leave any feedback there :)
