### ISSUE TITLE
Consider using sudo: false which allows to use container-based travis infrastructure

### ISSUE THREAD

**Issue by olifre** [mrueg/repoman-travis#6]
Unless I am mistaken, this project does not use sudo, so it would be possible: 
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
to easily migrate to container-based execution which gives somewhat higher performance (and faster build starts etc.). 

A simple
`sudo: false`
should be sufficient.

**Comment by olifre** [comment]
I'm sorry, of course you use sudo, to allow portage to run! 
Sorry again, let's close this...

**Comment by mrueg** [comment]
Yeah, I'm still looking for an easy way to avoid sudo.
