### ISSUE TITLE
I/O error : Attempt to load network entity http://www.gentoo.org/dtd/metadata.dtd

### ISSUE THREAD

**Issue by suhr** [mrueg/repoman-travis#7]
See https://travis-ci.org/suhr/muscraft/builds/104599532 as example.

**Comment by bor** [comment]
I have the same issue.

**Comment by mrueg** [comment]
herd was removed from metadata.dtd by some Gentoo developer. You need to remove the <herd> parts from your metadata.xml files.

**Comment by suhr** [comment]
This works, thanks!

But why did it say `I/O error : Attempt to load network entity http://www.gentoo.org/dtd/metadata.dtd`?

**Comment by ArsenShnurkov** [comment]
This issue is closed too early - https://github.com/gentoo/dotnet/issues/178
